import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Auction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bamboo.ico" />
      </Head>

        <div align="center" >
          <Image src="/lotus.png" width={72} height={72} />
        </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/auction">Auction!</a>
        </h1>

        <p className={styles.description}>
          Get started by clicking{' '}
          <code className={styles.code}>Auction</code>
        </p>

        <div className={styles.grid}>
          <a
            href="/space.jpg"
            className={styles.card}
          >
            <h2>NFT &rarr;</h2>
            <p>Show the NFT for Auction.</p>
          </a>

          <a
            href="introduction.html"
            className={styles.card}
          >
            <h2>Introduction &rarr;</h2>
            <p>
              Show the introduction.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}